### ISSUE TITLE
Add Portugal to creation flow

### ISSUE THREAD

**Issue by GrifP** [p2pu/erasmus-partner-site#10]

**Comment by GrifP** [comment]
From Claudia - There is no portuguese language in the end of this:”what is the primary language for this Learning circle”

![image](https://user-images.githubusercontent.com/7155640/81709244-bf351900-943f-11ea-9f88-f1ba16aca035.png)

**Comment by dirkcuys** [comment]
The option is there, but looks like it's a little more difficult to see when you need to vertically scroll for the form

![image](https://user-images.githubusercontent.com/121995/81827798-68ac0580-9539-11ea-8c69-8f3d20321531.png)
