### ISSUE TITLE
Add EU logo / link to project page somewhere on the landing pages

### ISSUE THREAD

**Issue by dirkcuys** [p2pu/erasmus-partner-site#5]

**Comment by GrifP** [comment]
In the footer of each team page add two icons, one for the project and one for the EU. (You can make them both grey if you think it looks better).

[Erasmus+ logo](https://www.google.com/search?q=erasmus%2B+logo&rlz=1C5CHFA_enUS726US727&sxsrf=ALeKk01Sf8SKOgBRcsUV5lvBDMM3grTEyw:1588272182493&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjHy_n55pDpAhVXg3IEHZpQBgwQ_AUoAXoECAsQAw&biw=1308&bih=878#imgrc=YREb2TQzSJkHYM)
Linking to EU page for all sites: https://ec.europa.eu/programmes/erasmus-plus/node_en

[Project logo](https://drive.google.com/drive/u/1/folders/1dSlc9TvHz17r-uch34Q1sCkDc8N4wD6H) (Anything in this folder)

Linking to a different page for each site:
- [x] POLAND: http://frsi.org.pl/projekt/learning-circles-in-libraries/
- [x] ROMANIA: http://www.progressfoundation.ro/learning-circles-3/
- [x] FINLAND: https://eoppimiskeskus.fi/projekti/learning-circles-in-libraries/
- [x] GERMANY: https://www.stadt-koeln.de/artikel/66407/index.html
- [x] PORTUGAL: https://www.blcs.pt/portal/default.aspx#

**Comment by GrifP** [comment]
@s-kennedy it looks like the project logo is pointing to p2pu.org -- can you direct it to the URLS I listed above?

**Comment by dirkcuys** [comment]
I added the links.

**Comment by s-kennedy** [comment]
Thanks Dirk!
